### ISSUE TITLE
机型用q35还是i440fx呢？

### ISSUE THREAD

**Issue by zml2zyx** [cmd2001/build-edk2-gvtd#4]
机型用q35还是i440fx呢？q35的性能不是强么。同时win10的虚拟机的“显示”选项是不是要修改为“无”？安装win10虚拟机的时候是“默认”

**Comment by cmd2001** [comment]
The Machine Type have to be `440fx`, since there is a `LPC/ISA bridge` on pci address `00:1f.0` when using `q35`, which is  conflict with iGPU.

For the second question, Display must be changed to `None`, otherwise qemu-kvm would prevent the VM from booting.
